# -*- coding: utf-8 -*-
"""atm_controller_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ky4pjRd-589PfXMqQg3LCRJGOGTM7Oyw
"""

class Bank:
    def verify_pin(self, card_number, pin):
        # For simplicity, let's assume any PIN is correct for demonstration purposes
        return True

    def get_account_balance(self, account_number):
        # For simplicity, let's return a predefined balance
        return 1000

    def deposit(self, account_number, amount):
        # For simplicity, let's assume the deposit is successful
        return True

    def withdraw(self, account_number, amount):
        # For simplicity, let's assume the withdrawal is successful
        return True


class ATM:
    def __init__(self, bank):
        self.bank = bank
        self.card_inserted = False
        self.pin_entered = False
        self.account_selected = False
        self.current_account_number = None

    def insert_card(self, card_number):
        # For simplicity, let's assume any card is valid
        self.card_inserted = True

    def enter_pin(self, pin):
        if self.card_inserted:
            # Verify the PIN with the bank
            if self.bank.verify_pin(self.current_account_number, pin):
                self.pin_entered = True
                return True
        return False

    def select_account(self, account_number):
        if self.pin_entered:
            # For simplicity, let's assume any account is valid
            self.account_selected = True
            self.current_account_number = account_number
            return True
        return False

    def see_balance(self):
        if self.account_selected:
            balance = self.bank.get_account_balance(self.current_account_number)
            return f"Your account balance is ${balance}"
        return "Account not selected"

    def deposit(self, amount):
        if self.account_selected:
            if self.bank.deposit(self.current_account_number, amount):
                return f"Deposited ${amount} successfully"
        return "Deposit failed"

    def withdraw(self, amount):
        if self.account_selected:
            if self.bank.withdraw(self.current_account_number, amount):
                return f"Withdrew ${amount} successfully"
        return "Withdrawal failed"


# Example usage:
bank = Bank()
atm = ATM(bank)

# Insert Card
atm.insert_card("13579")

# Enter PIN
atm.enter_pin("6420")

# Select Account
atm.select_account("507")

# See Balance
print(atm.see_balance())

# Deposit
print(atm.deposit(200))

# Withdraw
print(atm.withdraw(50))