# -*- coding: utf-8 -*-
"""ATM_controller.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TXy6UOIGE3EXBQk1Ubl4WOXoWzFom3eL
"""

class ATM:
    def __init__(self, bank):
        self.bank = bank
        self.card_inserted = False
        self.pin_entered = False
        self.account_selected = False
        self.current_account_number = None

    def insert_card(self, card_number):
        # card reader is not a scope of this task
        self.card_inserted = True

    def enter_pin(self, pin):
        if self.card_inserted:
            # Verify the PIN with the bank
            if self.bank.verify_pin(self.current_account_number, pin):
                self.pin_entered = True
                return True
        return False

    def select_account(self, account_number):
        if self.pin_entered:
            self.account_selected = True
            self.current_account_number = account_number
            return True
        return False

    def see_balance(self):
        if self.account_selected:
            balance = self.bank.get_account_balance(self.current_account_number)
            return f"Your account balance is ${balance}"
        return "Account not selected"

    def deposit(self, amount):
        if self.account_selected:
            if self.bank.deposit(self.current_account_number, amount):
                return f"Deposited ${amount} successfully"
        return "Deposit failed"

    def withdraw(self, amount):
        if self.account_selected:
            if self.bank.withdraw(self.current_account_number, amount):
                return f"Withdrew ${amount} successfully"
        return "Withdrawal failed"